version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /docker-creds/username
    DOCKER_REGISTRY_PASSWORD: /docker-creds/password
    DOCKER_REGISTRY_URL: /docker-registry/url
phases:
  install:
    runtime-versions:
      python: 3.12
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running tests..."
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/codepipeline-demo:latest" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/codepipeline-demo:latest"
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'
  # base-directory: codepipeline-demo
  # name: dev-artifacts
  # discard-paths: no

